### ISSUE TITLE
5 Character vanity address

### ISSUE THREAD

**Issue by sarahridgley** [celrenheit/alfred#2]
I keep getting this error when I try to do a 5 character vanity address:

took 18m32.6958567s
error opening backup: cipher: message authentication failed

Once this happens, alfred won't create any more accounts unless I completely delete and reinstall.  I was able to successfully get a 4 character one, so maybe that is the max? I couldn't find it in the documentation.

**Comment by celrenheit** [comment]
If you receive this error it is because the secret is wrong.
However, Alfred opened the database *after* generating the vanity address. So you receive `cipher: message authentication failed` by not entering the correct password but you know it until after alfred generates the vanity address... I'll fix this behavior.

>  I was able to successfully get a 4 character one, so maybe that is the max?

There is no max. The only max is the time you are willing to wait for (more than 4 chars should take some time) 18m is already good

**Comment by celrenheit** [comment]
It's fixed in v0.1.7

**Comment by celrenheit** [comment]
I've added the option to print seed (and address). This way, even if writing fails you still have those keys.
For example: `alfred new --print-seed --suffix AIR`
